### ISSUE TITLE
Missing Power Strip

### ISSUE THREAD

**Issue by jbhardman** [ZeliardM/homebridge-kasa-python#209]
### Type

Bug

### Summary

I have a power strip, Kasa KP303, that has worked with this plugin for about a year.
I just noticed today, it is missing in my Home app. Just disappeared.
I did everything, can't get it back. The device works in my Tapo/Kasa apps, Alexa as well. It is powered on and I can see it on my network. 
I uninstalled, restarted Homebridge, reinstalled the plugin. Nothing helps.
I have 2 other Kasa/Tapo devices, light switches, and those work great. Discovery picks them right up. The power strip is on the same wifi as those devices.
Even if I put the IP address in the Manual Devices list, it still is not found.
Logs attached.

What could I do?

### Details

Missing device that was previously working.

### Environment (Required for Bugs)

Plugin: v2.9.1

### Logs (If Relevant)

```text
[12/28/2025, 6:02:24 PM] [KasaPython] Restarting Process...
[12/28/2025, 6:02:24 PM] [KasaPython] Launched child bridge with PID 2294
[12/28/2025, 6:02:24 PM] [KasaPython] Loaded homebridge-kasa-python v2.9.1 child bridge successfully
[12/28/2025, 6:02:24 PM] [KasaPython] homebridge-kasa-python v2.9.1, node v22.21.1, homebridge v1.11.1, api v2.7 Initializing...
[12/28/2025, 6:02:25 PM] [KasaPython] Discovering devices using streaming...
[12/28/2025, 6:02:25 PM] [KasaPython] Discovery initiated: { status: 'discovery started' }
[12/28/2025, 6:02:25 PM] [KasaPython] Received device info for 10.0.2.51
[12/28/2025, 6:02:25 PM] [KasaPython] Adding HomeKit device: [Office Lights] dimmer [800634928454837B428561B12AB44DF0237CF7FB] at host [10.0.2.51]
[12/28/2025, 6:02:25 PM] [KasaPython] Received device info for 10.0.2.50
[12/28/2025, 6:02:25 PM] [KasaPython] Adding HomeKit device: [Master Bed Light ] dimmer [80242FA4ECBA2BE1350990B7C8119A10223C6638] at host [10.0.2.50]
[12/28/2025, 6:02:30 PM] [KasaPython] Device discovery complete.
```

**Comment by jbhardman** [comment]
I think the discovery is on port 20002/UDP. I can connect from the Homebridge host:

```
# nc -z -v -u 10.0.2.52 20002
Connection to 10.0.2.52 20002 port [udp/commtact-http] succeeded!
```

**Comment by ZeliardM** [comment]
@jbhardman I've pushed updates to the backend python-kasa library to resolve this. I'm waiting on several other things to be pushed out with it as well and then an update to be published for the library. Once the fixes are in the library, I can fix everything in my plug-in, but until then there is not much I can do. You can try enabling the Third-Party Compatibility in the Tapo app as well and see if that helps.

**Comment by jbhardman** [comment]
Ok, thanks for the update. What's strange is it worked for the longest time...? Any way, I enabled 3rd party access and rescanned for devices. No luck. I'll watch for updates.
Thanks!

**Comment by TinyMito** [comment]
I just purchased a KP303, even manually add the device IP. Still won't discover on the Homebridge at all.

**Comment by ZeliardM** [comment]
@jbhardman @TinyMito Would either of you be able to manually run a discover with the python-kasa CLI interface and get me the debug output from the Homebridge Web UI Terminal:
cd kasa-python
source .venv/bin/activate
kasa --debug --host IP_ADDRESS --username 'USERNAME' --password 'PASSWORD' discover

Please scrub any personal information you don't want shared publicly, but I need to see what the communication and encryption handling is done as when it fails. I am pretty sure it is because of the new_klap handling, but this fix has not been pushed to the backend library yet so the fix is not readily available for the plug-in.

**Comment by TinyMito** [comment]
@ZeliardM I clear all the accessories cache, reinstalled your plugin and the outlet shows up correctly and working. How odd! However! I am now seeing the same problem with HS200 light switch. I'll open a new thread if I can't resolve it on my own here. Also, is this normal - that it has no input to enter credential information after enabling this?

Apparently the HS200 v5.26 requires credential to work; I think.

<img width="1384" height="752" alt="Image" src="https://github.com/user-attachments/assets/ded8c6a7-7223-4fbf-8acf-34adfe7c4ef9" />

**Comment by ZeliardM** [comment]
@jbhardman Try adding the credentials and see if that works for you. Some of the newer devices with newer firmware require the credentials, even for Kasa devices.

**Comment by ZeliardM** [comment]
@jbhardman I fixed the credentials in the latest beta, v3.1.0-beta.2. Give that a shot and let me know if putting in the username and password resolves this issue. If so, close this out as completed.

**Comment by simonhaenisch** [comment]
Came back from vacation and I have the same issue... got two power strips P300, both the same, but one wasn't controllable anymore. So I updated the plugin to v3 and then the accessory disappeared. Tried that beta just now and credentials are there but it still only finds one device.

```
[14/01/2026, 07:06:38] [Kasa] homebridge-kasa-python v3.1.0-beta.2, node v22.15.0, homebridge v1.11.1, api v2.7 Initializing...
[14/01/2026, 07:06:38] Homebridge v1.11.1 (HAP v0.14.0) (Tapo) is running on port 38190.
[14/01/2026, 07:06:40] [Kasa] Starting device discovery (SSE)...
[14/01/2026, 07:06:40] [Kasa] Discovery initiated: 1 potential entries
[14/01/2026, 07:06:40] [Kasa] Discovered device: DeviceType.Strip_192.168.178.22 (192.168.178.22)
[14/01/2026, 07:06:40] [Kasa] Adding HomeKit device: [DeviceType.Strip_192.168.178.22] strip [<device-id>] at host [192.168.178.22]
[14/01/2026, 07:06:45] [Kasa] Device discovery complete.
```

But in the Tapo app I can see and control both devices. I just noticed there's a firmware update available there, so i'll try that now.

**Comment by simonhaenisch** [comment]
Actually I just noticed that the firmware update is only available for the power strip that's still working, the other one seems to have auto-upgraded. That's probably what broke it 🥲

Adding another reason to my list of why not to buy TP Link stuff anymore 🫠 A firmware update is why i needed this plugin in the first place, cause after the previous firmware update the devices just wouldn't work or be able to add into Homekit directly anymore.

Edit: of course with the new firmware version I'm still not able to add the device into my home directly ("accessory is not compatible with HomeKit") 😤

**Comment by ZeliardM** [comment]
@simonhaenisch Are you able to run a manual command for me against the device in the Homebridge Web UI Terminal:

cd kasa-python
source .venv/bin/activate
kasa --debug --host IP_ADDRESS --username 'USERNAME' --password 'PASSWORD' discover

This will tell me if the backend sees the device or not. Also do you have the hardware and firmware information for the device? Do you have Third Party Compatibility enabled in the Tapo App on your phone? If so can you turn it off and back on while the phone is on the same network as the devices?

I understand that you're frustrated and I'm not making excuses for TPLink but firmware updates on anything have a tendency to break stuff. TPLink has made a lot of changes lately to make their devices more secure which has been a problem for us in the community. Fixes are in the pipeline, it just takes time to get it right and to make sure that everyone's issues are resolved.

**Comment by ZeliardM** [comment]
@jbhardman Can you also make sure that Third Party Compatibility is enabled in your Tapo App on your phone as well? If it is, can you disable it and re-enable it with your phone and the devices on the same network? Sometimes this has resolved issues for the P100 and P110 plugs, but without the raw command information from the command I asked you to run above, I can't tell if it's the same problem or not. Try enabling it and the credentials and let me know.

**Comment by simonhaenisch** [comment]
Sry didn't have time until now. The devices are both TP Link Tapo P300 ([link](https://www.tp-link.com/de/home-networking/smart-plug/tapo-p300/)), hardware version 1.0, which I bought at the same time. The "working" firmware version is `1.0.16 Build 240529 Rel. 150326`. I put "working" in quotes because it's working with your Kasa plugin but not with HomeKit directly, which it used to with the firmware before that 😅 The new version available now is `1.4.2 Build 251219 Rel. 142654`.

I'll try the "third party compatibility" thing now, and run the commands.

**Comment by simonhaenisch** [comment]
@ZeliardM third party compatibility was disabled and enabling fixed it 🥳

I guess it's a new thing they introduced with this firmware? But they didn't mention anything other than "security improvements" in the changelog 🫠

Anyway thanks for your help, really appreciate it! And sry about the rant. It's just that they sold me a device with a sticker saying it's compatible with HomeKit, but then they broke that compatibility with a firmware upgrade, and their customer service was not great either... eventually an actual developer told me via email that the problem is a bug from Apple, which still doesn't make any sense to me. After living with the issue for a year, I got Homebridge and your plugin saved me 🙏 

![](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnQ3bWVpdHdyaWhjdzVleXNzcWRnamk5ZzdlaXBudXIyNXljOTAydCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fWfowxJtHySJ0SGCgN/giphy.gif)

**Comment by ZeliardM** [comment]
@simonhaenisch Glad I could help!

@jbhardman If you could, try the Third Party Compatibility and let me know if that resolves the issues for you as well.

**Comment by ZeliardM** [comment]
@jbhardman Can you try Third Party Compatibility and let me know if that resolved the issues and if we can close this out?

**Comment by ZeliardM** [comment]
@jbhardman Can you try Third Party Compatibility and let me know if that resolved the issues and if we can close this out?

**Comment by ZeliardM** [comment]
@jbhardman Can you try Third Party Compatibility and let me know if that resolved the issues and if we can close this out?

**Comment by ZeliardM** [comment]
@jbhardman can you try the latest release and the Third Party Compatibility and let me know if the issue is resolved? If so, let’s close this out.

**Comment by ZeliardM** [comment]
@jbhardman can you try the latest release and the Third Party Compatibility and let me know if the issue is resolved? If so, let’s close this out.

**Comment by natrlhy** [comment]
I have a few KP303's the latest beta build isn't seeing the devices either. If I ran `kasa --debug --host IP_ADDRESS --username 'USERNAME' --password 'PASSWORD' discover` what IP do I give it?

I do have authentication setup and I'm not seeing the power strips.

EDIT: I updated the Third-Party Compatibility in my Kasa App and restarted the child bridge. Looks like I can see all the power strip devices now.

Other notes: 

KP303
HW version 2.0
FW version 1.1.2

**Comment by ZeliardM** [comment]
@simonhaenisch @natrlhy @TinyMito @jbhardman I have been working on rebuilding things here. I am in the process of making my own TypeScript library and a new plugin. This should resolve the issues. Once everything is down and ready to release, I will let everyone know.
